'use client';
import {t} from '@/lib/game/translate';

import {Shield,KeyRound,RotateCcw,Eye} from 'lucide-react';
import {CORE_NODES,hasAccountSurface,type NodeId,type NodeState,type Deployment} from '@/lib/game/engine';

export function DefenseFlags({node}:{node:Pick<NodeState,'shield'|'auth'|'backup'|'sensor'>}){
 return <>{t(node.shield>0&&<span className="guard-ddos" title={t("Анти-DDoS")}><Shield size={10}/>{t(node.shield)}</span>)}{t(node.auth>0&&<span className="guard-auth" title={t("Защита аккаунтов")}><KeyRound size={10}/>{t(node.auth)}</span>)}{t(node.backup&&<RotateCcw className="guard-backup" size={11} aria-label={t("Восстановление")}/>)}{t(node.sensor&&<Eye size={11} aria-label={t("Датчик")}/>)}</>;
}
export function DefenseDetails({node,nodeId}:{node:NodeState;nodeId:NodeId}){
 return <div className="counter-details"><div className={node.shield?'protected':''}><Shield size={18}/><strong>{t("Анти-DDoS ")}<b>{t(node.shield)}/2</b></strong><span>{t(!node.income?'Этот узел не приносит доход и не является целью DDoS.':node.shield?'Отразит DDoS. Фишинг и саботаж проходят.':'DDoS: потеря дохода и денег за срыв контрактов.')}</span></div><div className={node.auth?'protected':''}><KeyRound size={18}/><strong>{t("Аккаунты ")}<b>{t(node.auth)}/2</b></strong><span>{t(!hasAccountSurface(nodeId)?'У узла нет пользовательской учётной записи для фишинга.':node.auth?'Отразит фишинг или подмену платежа. Технический вход проходит.':'Фишинг: доступ к учётной записи. Подмена платежа: кража денег после проникновения.')}</span></div><div className={node.backup?'protected':''}><RotateCcw size={18}/><strong>{t("Восстановление ")}<b>{t(node.backup?'1/1':'0/1')}</b></strong><span>{t(!node.income?'На этом узле нет дохода для саботажа. Очистка и изоляция всё ещё важны.':node.backup?'Отразит саботаж и удалит доступ. DDoS и фишинг проходят.':'Саботаж после проникновения: сбой и денежный штраф.')}</span></div></div>;
}
export function CounterGuide(){return <div className="counter-guide"><strong>{t("Подберите атаку под защиту")}</strong><span><Shield size={17}/>{t(" Анти-DDoS отражает DDoS")}</span><span><KeyRound size={17}/>{t(" Защита аккаунтов отражает фишинг и подмену платежа")}</span><span><RotateCcw size={17}/>{t(" Восстановление отражает саботаж")}</span><p>{t("Заряд контрмеры расходуется. Другие угрозы проходят. Разведка раскрывает защиты; зелёная рамка отмечает уязвимую цель, оранжевая — цель с подходящей контрмерой.")}</p></div>;}

const protectionTypes=[{field:'shields',label:'Анти-DDoS',icon:Shield,max:2},{field:'auth',label:'Аккаунты',icon:KeyRound,max:2},{field:'backups',label:'Восстановление',icon:RotateCcw,max:1},{field:'sensors',label:'Датчик',icon:Eye,max:1}] as const;
export function SetupProtection({deployment,index,spent,onChange}:{deployment:Deployment;index:number;spent:number;onChange:(value:Deployment)=>void}){
 return <div className="protection-setup">{t(protectionTypes.map(({field,label,icon:Icon,max})=>{const values=deployment[field]??[0,0,0,0,0],value=values[index],account=hasAccountSurface(CORE_NODES[index].id),applicable=field==='sensors'||(field==='auth'?account:!account);const change=(n:number)=>onChange({...deployment,[field]:values.map((v,i)=>i===index?n:v)});return <div key={field}><span><Icon size={16}/><span>{t(label)}{t(!applicable&&<small>{t(field==='auth'?'Нет учётной записи':'Только доходные серверы')}</small>)}</span></span><button disabled={!value} aria-label={t(`Убрать: ${label}`)} onClick={()=>change(value-1)}>−</button><b>{t(value)}/{t(max)}</b><button disabled={!applicable||spent>=4||value>=max} aria-label={t(`Добавить: ${label}`)} onClick={()=>change(value+1)}>+</button></div>;}))}</div>;
}
