'use client';
import {Shield,KeyRound,RotateCcw,Copy,Wifi,RefreshCw} from 'lucide-react';
import {COUNTER_LABELS,RESERVE_COST,actionStatus,type View,type Action,type Countermeasure} from '@/lib/game/engine';

export function ReservePanel({view,busy,onAction}:{view:View;busy:boolean;onAction:(a:Action)=>void}){
 const me=view.players[view.viewer];
 return <div className="reserve-panel"><p>{RESERVE_COST} кредитов · 1 действие.<br/>Действует до первого подходящего удара.</p>{me.reserve&&me.reserve!=='hidden'&&<strong className="reserve-active">На дежурстве: {COUNTER_LABELS[me.reserve]}</strong>}<div className="reserve-options">{([{counter:'ddos',icon:Shield,label:'Против DDoS',text:'Сохранить доход и контракты.'},{counter:'auth',icon:KeyRound,label:'Защита аккаунтов',text:'От фишинга или подмены платежа.'},{counter:'backup',icon:RotateCcw,label:'Против саботажа',text:'Отразить сбой и удалить доступ.'}] as const).map(({counter,icon:Icon,label,text})=>{const action:Action={type:'reserve',counter:counter as Countermeasure},status=actionStatus(view,action);return <button key={counter} disabled={busy||!status.ok} onClick={()=>onAction(action)}><Icon size={22}/><strong>{label}</strong><span>{text}</span>{!status.ok&&<small>{status.reason}</small>}</button>;})}</div><details className="reserve-hint"><summary>Как это работает?</summary><p>Отражает один удар выбранного типа по любому узлу. Соперник видит готовность, но тип узнает только при отражении. Постоянная защита узла расходуется первой. Неиспользованное дежурство сохраняется между ходами. Тип можно заменить за полную стоимость; подготовка доступна один раз за свой ход.</p></details></div>;
}

export function RoomPanel({code,connection,opponentStatus,expiresAt,onCopy,onReconnect}:{code:string;connection:string;opponentStatus:string;expiresAt?:number;onCopy:()=>void;onReconnect:()=>void}){
 return <div className="room-panel"><div className="room-invite"><span>Код комнаты</span><strong>{code}</strong><button className="primary-button" onClick={onCopy}><Copy size={18}/> Приглашение</button></div><div className="room-connection" role="status"><Wifi size={19}/><span>{connection}<small>{opponentStatus}</small></span><button className="quiet-button" onClick={onReconnect} aria-label="Проверить связь"><RefreshCw size={18}/></button></div><p>Если вкладка закроется, откройте игру в этом же браузере и нажмите «Вернуться в комнату». После обрыва связи дождитесь обновления поля.</p><p className="muted-small">Комната хранится до {expiresAt?new Date(expiresAt).toLocaleString('ru-RU',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'следующего дня'}. За отключение поражение не засчитывается.</p><details><summary>Как провести первый тест вдвоём</summary><ol><li>Откройте веб-версию на двух устройствах и отправьте второму игроку приглашение в комнату.</li><li>На разных устройствах подтвердите расстановки и сыграйте партию.</li><li>В середине матча обновите страницу: деньги, карты и очередь хода должны сохраниться.</li><li>После результата скопируйте отчёт. Сыграйте реванш: первый ход поменяется.</li></ol><p>Для обратной связи: модель телефона, удобство выбора карт, ощущение силы атак и защиты.</p></details></div>;
}

export function matchReport(view:View,code?:string){
 return [`КОНТУР 0.5 · тест ${code??view.mode} · матч ${view.matchNumber}`,`Завершение: ${view.logs.some(l=>l.text.includes('сдаётся.'))?'сдача игрока':'сравнение казны'}. Раундов: ${view.round}. Первый ход: компания ${view.firstPlayer+1}. Победитель: ${view.winner===null?'ничья':'компания '+(view.winner+1)}.`,...view.players.map((p,i)=>{const s=view.stats?.[i];return `Компания ${i+1}: казна ${p.money}, доход за матч ${p.earned}${s?`, потрачено ${s.spent}; карты и дежурства: атака/защита/экономика ${s.attacks}/${s.defenses}/${s.economy}; отражено ${s.blocked}; украдено ${s.stolen}; потеряно из казны ${s.cashLost}`:''}.`;})].join('\n');
}
